<?php if ( ! defined( 'ABSPATH' ) ) {
	die( 'Direct access forbidden.' );
}

if( ! function_exists( 'oktan_filter_social_icons_icon_set' ) ) :
function oktan_filter_social_icons_icon_set( $sets ) {
	$sets['social-icons'] = array(
		'font-style-src'  => OKTAN_THEME_URI . ( '/css/font-awesome.css' ),
		'container-class' => '', // some fonts need special wrapper class to display properly
		'groups'          => array(
			'all' => esc_html__( 'All', 'oktan' ),
		),
		'icons'           => array(
			'fa fa-facebook'             => array( 'group' => 'all' ),
			'fa fa-twitter'              => array( 'group' => 'all' ),
			'fa fa-instagram'            => array( 'group' => 'all' ),
			'fa fa-linkedin'             => array( 'group' => 'all' ),
			'fa fa-telegram'             => array( 'group' => 'all' ),
			'fa fa-pinterest-p'          => array( 'group' => 'all' ),
			'fa fa-google'               => array( 'group' => 'all' ),
			'fa fa-flickr'               => array( 'group' => 'all' ),
			'fa fa-youtube'              => array( 'group' => 'all' ),
			'fa fa-vimeo'                => array( 'group' => 'all' ),
			'fa fa-share-alt'            => array( 'group' => 'all' ),
			'fa fa-soundcloud'           => array( 'group' => 'all' ),
			'fa fa-facebook-official'    => array( 'group' => 'all' ),
			'fa fa-facebook-square'      => array( 'group' => 'all' ),
			'fa fa-twitter-square'       => array( 'group' => 'all' ),
			'fa fa-500px'                => array( 'group' => 'all' ),
			'fa fa-adn'                  => array( 'group' => 'all' ),
			'fa fa-amazon'               => array( 'group' => 'all' ),
			'fa fa-android'              => array( 'group' => 'all' ),
			'fa fa-angellist'            => array( 'group' => 'all' ),
			'fa fa-apple'                => array( 'group' => 'all' ),
			'fa fa-behance-square'       => array( 'group' => 'all' ),
			'fa fa-behance'              => array( 'group' => 'all' ),
			'fa fa-bitbucket-square'     => array( 'group' => 'all' ),
			'fa fa-bitbucket'            => array( 'group' => 'all' ),
			'fa fa-bitcoin'              => array( 'group' => 'all' ),
			'fa fa-black-tie'            => array( 'group' => 'all' ),
			'fa fa-btc'                  => array( 'group' => 'all' ),
			'fa fa-buysellads'           => array( 'group' => 'all' ),
			'fa fa-cc-amex'              => array( 'group' => 'all' ),
			'fa fa-cc-diners-club'       => array( 'group' => 'all' ),
			'fa fa-cc-discover'          => array( 'group' => 'all' ),
			'fa fa-cc-jcb'               => array( 'group' => 'all' ),
			'fa fa-cc-mastercard'        => array( 'group' => 'all' ),
			'fa fa-cc-paypal'            => array( 'group' => 'all' ),
			'fa fa-cc-stripe'            => array( 'group' => 'all' ),
			'fa fa-cc-visa'              => array( 'group' => 'all' ),
			'fa fa-chrome'               => array( 'group' => 'all' ),
			'fa fa-codepen'              => array( 'group' => 'all' ),
			'fa fa-connectdevelop'       => array( 'group' => 'all' ),
			'fa fa-contao'               => array( 'group' => 'all' ),
			'fa fa-creative-commons'     => array( 'group' => 'all' ),
			'fa fa-css3'                 => array( 'group' => 'all' ),
			'fa fa-dashcube'             => array( 'group' => 'all' ),
			'fa fa-delicious'            => array( 'group' => 'all' ),
			'fa fa-deviantart'           => array( 'group' => 'all' ),
			'fa fa-digg'                 => array( 'group' => 'all' ),
			'fa fa-dribbble'             => array( 'group' => 'all' ),
			'fa fa-dropbox'              => array( 'group' => 'all' ),
			'fa fa-drupal'               => array( 'group' => 'all' ),
			'fa fa-empire'               => array( 'group' => 'all' ),
			'fa fa-expeditedssl'         => array( 'group' => 'all' ),
			'fa fa-firefox'              => array( 'group' => 'all' ),
			'fa fa-fonticons'            => array( 'group' => 'all' ),
			'fa fa-forumbee'             => array( 'group' => 'all' ),
			'fa fa-foursquare'           => array( 'group' => 'all' ),
			'fa fa-ge'                   => array( 'group' => 'all' ),
			'fa fa-get-pocket'           => array( 'group' => 'all' ),
			'fa fa-gg-circle'            => array( 'group' => 'all' ),
			'fa fa-gg'                   => array( 'group' => 'all' ),
			'fa fa-git-square'           => array( 'group' => 'all' ),
			'fa fa-git'                  => array( 'group' => 'all' ),
			'fa fa-github-alt'           => array( 'group' => 'all' ),
			'fa fa-github-square'        => array( 'group' => 'all' ),
			'fa fa-github'               => array( 'group' => 'all' ),
			'fa fa-gittip'               => array( 'group' => 'all' ),
			'fa fa-google-plus-square'   => array( 'group' => 'all' ),
			'fa fa-google-plus'          => array( 'group' => 'all' ),
			'fa fa-google-wallet'        => array( 'group' => 'all' ),
			'fa fa-hacker-news'          => array( 'group' => 'all' ),
			'fa fa-houzz'                => array( 'group' => 'all' ),
			'fa fa-html5'                => array( 'group' => 'all' ),
			'fa fa-internet-explorer'    => array( 'group' => 'all' ),
			'fa fa-ioxhost'              => array( 'group' => 'all' ),
			'fa fa-joomla'               => array( 'group' => 'all' ),
			'fa fa-jsfiddle'             => array( 'group' => 'all' ),
			'fa fa-lastfm-square'        => array( 'group' => 'all' ),
			'fa fa-lastfm'               => array( 'group' => 'all' ),
			'fa fa-leanpub'              => array( 'group' => 'all' ),
			'fa fa-linkedin-square'      => array( 'group' => 'all' ),
			'fa fa-linux'                => array( 'group' => 'all' ),
			'fa fa-maxcdn'               => array( 'group' => 'all' ),
			'fa fa-meanpath'             => array( 'group' => 'all' ),
			'fa fa-medium'               => array( 'group' => 'all' ),
			'fa fa-odnoklassniki-square' => array( 'group' => 'all' ),
			'fa fa-odnoklassniki'        => array( 'group' => 'all' ),
			'fa fa-opencart'             => array( 'group' => 'all' ),
			'fa fa-openid'               => array( 'group' => 'all' ),
			'fa fa-opera'                => array( 'group' => 'all' ),
			'fa fa-optin-monster'        => array( 'group' => 'all' ),
			'fa fa-pagelines'            => array( 'group' => 'all' ),
			'fa fa-paypal'               => array( 'group' => 'all' ),
			'fa fa-pied-piper-alt'       => array( 'group' => 'all' ),
			'fa fa-pied-piper'           => array( 'group' => 'all' ),
			'fa fa-pinterest-square'     => array( 'group' => 'all' ),
			'fa fa-pinterest'            => array( 'group' => 'all' ),
			'fa fa-qq'                   => array( 'group' => 'all' ),
			'fa fa-ra'                   => array( 'group' => 'all' ),
			'fa fa-rebel'                => array( 'group' => 'all' ),
			'fa fa-reddit-square'        => array( 'group' => 'all' ),
			'fa fa-reddit'               => array( 'group' => 'all' ),
			'fa fa-paper-plane'               => array( 'group' => 'all' ),
			'fa fa-renren'               => array( 'group' => 'all' ),
			'fa fa-safari'               => array( 'group' => 'all' ),
			'fa fa-sellsy'               => array( 'group' => 'all' ),
			'fa fa-share-alt-square'     => array( 'group' => 'all' ),
			'fa fa-share-alt'            => array( 'group' => 'all' ),
			'fa fa-shirtsinbulk'         => array( 'group' => 'all' ),
			'fa fa-simplybuilt'          => array( 'group' => 'all' ),
			'fa fa-skyatlas'             => array( 'group' => 'all' ),
			'fa fa-skype'                => array( 'group' => 'all' ),
			'fa fa-slack'                => array( 'group' => 'all' ),
			'fa fa-slideshare'           => array( 'group' => 'all' ),
			'fa fa-spotify'              => array( 'group' => 'all' ),
			'fa fa-stack-exchange'       => array( 'group' => 'all' ),
			'fa fa-stack-overflow'       => array( 'group' => 'all' ),
			'fa fa-steam-square'         => array( 'group' => 'all' ),
			'fa fa-steam'                => array( 'group' => 'all' ),
			'fa fa-stumbleupon-circle'   => array( 'group' => 'all' ),
			'fa fa-stumbleupon'          => array( 'group' => 'all' ),
			'fa fa-tencent-weibo'        => array( 'group' => 'all' ),
			'fa fa-trello'               => array( 'group' => 'all' ),
			'fa fa-tripadvisor'          => array( 'group' => 'all' ),
			'fa fa-tumblr-square'        => array( 'group' => 'all' ),
			'fa fa-tumblr'               => array( 'group' => 'all' ),
			'fa fa-twitch'               => array( 'group' => 'all' ),
			'fa fa-viacoin'              => array( 'group' => 'all' ),
			'fa fa-vimeo-square'         => array( 'group' => 'all' ),
			'fa fa-vine'                 => array( 'group' => 'all' ),
			'fa fa-vk'                   => array( 'group' => 'all' ),
			'fa fa-wechat'               => array( 'group' => 'all' ),
			'fa fa-weibo'                => array( 'group' => 'all' ),
			'fa fa-weixin'               => array( 'group' => 'all' ),
			'fa fa-wikipedia-w'          => array( 'group' => 'all' ),
			'fa fa-windows'              => array( 'group' => 'all' ),
			'fa fa-wordpress'            => array( 'group' => 'all' ),
			'fa fa-xing-square'          => array( 'group' => 'all' ),
			'fa fa-xing'                 => array( 'group' => 'all' ),
			'fa fa-y-combinator'         => array( 'group' => 'all' ),
			'fa fa-yahoo'                => array( 'group' => 'all' ),
			'fa fa-yc'                   => array( 'group' => 'all' ),
			'fa fa-yelp'                 => array( 'group' => 'all' ),
			'fa fa-youtube-play'         => array( 'group' => 'all' ),
			'fa fa-youtube-square'       => array( 'group' => 'all' ),
		),
	);

	return $sets;
}
endif; //oktan_filter_social_icons_icon_set

add_filter( 'fw_option_type_icon_sets', 'oktan_filter_social_icons_icon_set' );